### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [fantasyui-com/cowpea#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by fantasyui-com** [comment]
Cow Pea is just a tiny program, but if you send a PR, I'll merge it.

**Comment by geopic** [comment]
Thanks, I'll set about doing it now and will make a PR.

**Comment by fantasyui-com** [comment]
@geopic Done.

If you like writing poems take a look at https://github.com/fantasyui-com/rhy it helps you find rhymes.

If you are bored, I write an open source video book about growing up, it is mostly YouTube videos: https://westland-valhalla.github.io/warrior/

I also write long winded poetry here: https://news.catpea.com/

Thanks for helping.
